import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ApolloSetting from "@/common/settings/apollo-setting";

// Pretendard Variable 폰트를 로컬에서 불러옵니다.
const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  weight: "100 900", // 100부터 900까지 모든 굵기를 지정합니다.
});

export const metadata: Metadata = {
  title: "트립토크 여행게시판",
  description: "Generated by create next app",
};

interface IProps {
  children: React.ReactNode;
}

export default function RootLayout(props: IProps) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased`}>
        <ApolloSetting allpage={props.children}/>
      </body>
    </html>
  );
}